#! /bin/sh
####      Autostart Apps        ######

## Launch sxhkd hot key binding
sxhkd &

## Launch Picom Compsitor
#picom --config $HOME/.config/picom/picom.conf &
picom --experimental-backend &

## Launch Polybar
#polybar mybar &
$HOME/.config/polybar/launch.sh &

## Set Wallpapers
# feh --bg-fill --randomize ~/wallpaper/* &
feh --bg-fill $HOME/Pictures/nordic.png &

## Network Manager
nm-applet &

## Set both english & arabic layout
setxkbmap -layout us,ar &

## hide Mouse cursor while not in use
unclutter --timeout 2 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        3 
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config swallow_first_click   true
bspc config focus_follows_pointer true

bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#b8bb26"

# Window Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
